### ISSUE TITLE
Create copy sets from BMS file

### ISSUE THREAD

**Issue by dvag-Matthias-Rudolph** [NEORIS-ZDEVOPS/BMS-Designer#6]
Can the BMS Painter create copysets from BMS files?

**Comment by antonkc** [comment]
The extension doesn't support exporting to copysets. but we are interested in your usecase to extend capabilities.

**Comment by antonkc** [comment]
@dvag-Matthias-Rudolph 
Are you perhaps refering to copybooks instead of copysets?

**Comment by dvag-Matthias-Rudolph** [comment]
@antonkc 

Here's what I mean:
File AAAAA.BMS contains perhaps:
...
AAAAA DFHMDFATTRB=(FSET,UNPROT),LENGTH=7,POS=(1,5) 
...
 
For this BMS-File, we need a Copy-File, with this content:
02 AAAAAL COMP PIC S9(4). 
02 AAAAAF PIC X. 
02 AAAAAI PIC X(7). 

Where 
AAAAAL field length
AAAAAF prot / unprot
AAAAAI input field

**Comment by FALLAI-Denis** [comment]
Hi,

In my humble opinion, but it is up to the NEORIS development team to decide, I think that we should not reinvent solutions that already exist.
I think that what should be implemented is the construction of a compilation "SYSPARM(DSECT),DECK,NOOBJECT" job, submitted via the Zowe APIs (since the extension is already dependent on these APIs), and to retrieve the result locally.
This script can also be implemented independently of this BMS map editing extension.
The downside of this solution is that it requires a z system to compile the map and create the copybook.

Regards,
